### ISSUE TITLE
Setup github actions ci in sdk-kernel

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/sdk-kernel#1]
Draw from the examples in:

https://github.com/networkservicemesh/sdk/blob/master/.github/workflows/ci.yaml

and

https://github.com/networkservicemesh/sdk-vppagent/blob/master/.github/workflows/ci.yaml

Will also require moving across and adapting:

.license
.golangci-lint.yaml
.go-header.yaml
.yamllint.yml
etc

**Comment by rktidwell** [comment]
I'll take a crack at this

**Comment by edwarnicke** [comment]
Well done!
