### ISSUE TITLE
Reorder inject, rename chain elements

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk-kernel#102]
# Issue
Existing `inject`, `rename` chain elements makes possible to use them in chain only as:
```
... -> rename -> ... -> inject -> ...
```
It results in issue when multiple clients request for the same kernel interface name and some of them fail.
# Expected solution
Rework these elements so it will be possible to use them in reversed order (even if **only** in reversed order).
```
... -> inject -> ... -> rename -> ...
```

**Comment by Bolodya1997** [comment]
@pperiyasamy
Can you please take a look at this? I guess this can affect your cases if there are multiple clients requesting SR-IOV kernel mechanism with the same kernel interface name.
If not, I am not pushing you to fix it :)

**Comment by pperiyasamy** [comment]
@Bolodya1997 can we merge both inject and rename chain elements functionality into single chain element ? 
this would make things simpler in renaming `ifName` and renaming back original name (of course on target netns) ?

**Comment by Bolodya1997** [comment]
Yes, it is a good idea.
