### ISSUE TITLE
Migrate SRIOV forwarder PR (kernel interfaces) to new style xconnect NS

### ISSUE THREAD

**Issue by przemeklal** [networkservicemesh/sdk-kernel#11]
Refactor the initial implementation of the sriov-forwarder network service SDK in a style similar to the sdk-vppagent, using kernel mechanism from the API repo.

**Comment by przemeklal** [comment]
Original PR for reference https://github.com/networkservicemesh/networkservicemesh/pull/1925

**Comment by przemeklal** [comment]
Looking for some feedback on the PR #13

**Comment by Bolodya1997** [comment]
SR-IOV forwarder is actually ready in some different way: https://github.com/networkservicemesh/cmd-forwarder-sriov.

**Comment by denis-tingaikin** [comment]
Closing by https://github.com/networkservicemesh/sdk-kernel/issues/11#issuecomment-762049044
