### ISSUE TITLE
Rework netNSServer

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk-kernel#149]
# Issue
`netNSServer` locks OS thread before calling `next.Request`/`next.Close` - it can lead us to performance issues if someone puts in somewhere in wrong place in the chain:
https://github.com/networkservicemesh/sdk-kernel/blob/dd46e4efdfe2292460aee5e792053705d4c92ce7/pkg/kernel/networkservice/netns/server.go#L56-L59
https://github.com/networkservicemesh/sdk-kernel/blob/dd46e4efdfe2292460aee5e792053705d4c92ce7/pkg/kernel/networkservice/netns/server.go#L82-L85

# Solution
Pass chain that should be executed in another net NS as a constructor parameter, so it would be like a subchain wrapper:
```go
	// ...
	netns.NewServer(
		rename.NewServer(),
		ipcontext.NewServer(),
	),
	// ...
```

**Comment by Chunosov** [comment]
Is not actual, since this chain element is not used later on: https://github.com/networkservicemesh/sdk-sriov/commit/ac32f9866ff5571a44ef97ef9b8360d8c2f84207

**Comment by denis-tingaikin** [comment]
Resolved by https://github.com/networkservicemesh/sdk-kernel/pull/436
