### ISSUE TITLE
inject, rename support with client implementation

### ISSUE THREAD

**Issue by pperiyasamy** [networkservicemesh/sdk-kernel#226]
The sdk-kernel repo has interface inject and rename support available for ns client container with server implementation, can we have similar support available for endpoint with relevant client implementation ?
This would help forwarder(s) to inject sriov type of VFs into endpoint container.

**Comment by denis-tingaikin** [comment]
Sounds good to me. Be free to open PR :) 

/cc @edwarnicke

**Comment by pperiyasamy** [comment]
sure, thanks. I will open a PR.

/cc @JanScheurich

**Comment by edwarnicke** [comment]
@pperiyasamy Could you say more about what you are looking to do here?
