### ISSUE TITLE
ethernetcontext and ipcontext client

### ISSUE THREAD

**Issue by pperiyasamy** [networkservicemesh/sdk-kernel#227]
The sdk-kernel repo contains ethernetcontext and ipcontext packages which support configuring mac address, ip and routes on network service client container, can we have client.go module so that same support is available for endpoint container. Most of the generic code can be moved  under common.go.
There is also netns server code which runs subsequent server handler code under client container network namespace.
Should we also have such implementation for running ipcontext client for endpoint container ? or can that logic be part of ipcontext client module itself ?

**Comment by Bolodya1997** [comment]
I guess creating `ipcontext` client is a good idea.

**Comment by edwarnicke** [comment]
@Bolodya1997 @pperiyasamy Might it make more sense to consider moving:

https://github.com/networkservicemesh/sdk-vpp/tree/main/pkg/networkservice/connectioncontextkernel

to sdk-kernel?  Please note, doing so would also imply moving:

https://github.com/networkservicemesh/sdk-vpp/tree/main/pkg/tools/mechutils

@pperiyasamy @Bolodya1997 Thoughts?

**Comment by edwarnicke** [comment]
@pperiyasamy I also have PRs for:

[Implement connectioncontextkernel/ethernetcontext/getmac](https://github.com/networkservicemesh/sdk-vpp/issues/34)
[Implement connectioncontext/ethernetcontext/macaddress](https://github.com/networkservicemesh/sdk-vpp/issues/33)
[Implement connectioncontextkernel/ethernetcontext/macaddress](https://github.com/networkservicemesh/sdk-vpp/issues/32)

That might be interesting to you as sources of suggestions... if we decide to move connectioncontextkernel to sdk-kernel, we probably want to consider implementing those here as well.

**Comment by pperiyasamy** [comment]
@edwarnicke yes, we can merge sdk-vpp's contextcontextkernel and sdk-kernel's ethernetcontext/ipcontext packages and have it under sdk-kernel/pkg/kernel/networkservice/connectioncontextkernel having both client and server handlers and make vpp and sriov forwarders consume it from this package.  does it make sense ?
