### ISSUE TITLE
VF not moved into host net namespace

### ISSUE THREAD

**Issue by pperiyasamy** [networkservicemesh/sdk-kernel#333]
When NSC and NSE are deleted together with `kubectl delete -k .` on this [example](https://github.com/Nordix/nsm-deployments-k8s/tree/ovs-example/examples/use-cases/SmartVF2SmartVF), then VF attached on the endpoint container is not freed up and can't get moved into host net namespace.

This is mainly because inject client element tried to get into container net namespace, but this is already closed.

 Need to find out a way to properly move the device back into host net namespace so that it should be ready for next allocation (because device plugin server already freed up its token from the pool)

**Comment by pperiyasamy** [comment]
have tried with [caching](https://github.com/Nordix/nsm-sdk-kernel/commit/28d84262ab8c1390ee15da6adb0f69aac5a61801) net ns id into metadata in inject client chain element for moving back interface into host net namespace, but it fails with error `failed to get net interface: icmp-respo-e0c4: Link not found`, but the device is never moved back into host nets anytime after this unless nsm mgr pod is deleted.

```
0000:84:00.2 'MT27800 Family [ConnectX-5 Virtual Function] 1018' if=smartvf0_0 drv=mlx5_core unused=
0000:84:00.3 'MT27800 Family [ConnectX-5 Virtual Function] 1018' if= drv=mlx5_core unused= 
```

after nsm mgr daemon set deletion,

```
0000:84:00.2 'MT27800 Family [ConnectX-5 Virtual Function] 1018' if=smartvf0_0 drv=mlx5_core unused=
0000:84:00.3 'MT27800 Family [ConnectX-5 Virtual Function] 1018' if=icmp-respo-e0c4 drv=mlx5_core unused=

```

**Comment by edwarnicke** [comment]
@Bolodya1997 How had we previously dealt with reuse of VFs for the kernel case?  Have we seen this before?

**Comment by pperiyasamy** [comment]
@edwarnicke your suggestion (i.e. Don’t close the netns for the NSE until after you’ve moved its VF back to the host netns as part of the Close process) made the trick :) and it's working.
