### ISSUE TITLE
Missing policy routes

### ISSUE THREAD

**Issue by ljkiraly** [networkservicemesh/sdk-kernel#685]
Some of the routes are missing from NSC. After deployment the routes were set but after a while they disappeared. The trigger is unknown.
The problem was seen on NSMv1.13.2.
In this topology 4 NS (one NSE  provides one NS) and 4 NSC was deployed and each NSC connects to each NS. For one connection the routes are missing from NSC.
The relevant log printouts are already rotated out when the issue was detected.
The reproduction is in progress, but since we don't really know what caused this behavior it is difficult to provoke the issue.

**Comment by ljkiraly** [comment]
Verification in progress.

**Comment by denis-tingaikin** [comment]
Hi @ljkiraly ,

How is going verification?

**Comment by ljkiraly** [comment]
No issue found since the fix is deployed, so I consider the problem solved
